### ISSUE TITLE
Typo in the project name?

### ISSUE THREAD

**Issue by jedisct1** [psve/argis-js#1]
Hi!

And thanks for this implementation!

By the way, if you wrote it from the specification (looks like this is the case according to the function names), your feedback is more than welcome.

I noticed that the project name is `argis`. Is that intentional?

**Comment by psve** [comment]
Ah, I must have been in too much of a hurry when I pushed this. I have fixed the name here and on the Kotlin repository. Thank you for making me aware!

The specification is generally good, it helped clear up a few things compared to the original paper. Nice work!

If I find some time I might implement Aegis-256 as well.
